ebean:
datasource:
  default: app
  app:
    databaseUrl: jdbc:mysql://localhost:3306/app
    databaseDriver: com.mysql.cj.jdbc.Driver
    username: app
    password: app
#    cachePrepStmts: true
#    prepStmtCacheSize: 250
    backgroundExecutorSchedulePoolSize: 200
